### ISSUE TITLE
Split internal and external installation files

### ISSUE THREAD

**Issue by jensg-st** [knative-extensions/net-contour#1000]
We are using contour only internally and our process is to install it with YAML followed by an immediate deletion of the external namespace `contour-external`. That works of course but I'm wondering if it is possible to split the YAML into the external and internal components?

**Comment by dprotaso** [comment]
Curious how are you installing Contour?

I wonder if we could add a label to distinguish between the two - then you could use [`kubect apply`](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#apply) with the label selector (`-l`)

**Comment by montag** [comment]
It would be handy if the configs were split.
