### ISSUE TITLE
dispatch/path* 503s

### ISSUE THREAD

**Issue by mattmoor** [knative-extensions/net-contour#252]
The continuous build hit a few 503s in the "dispatch/path" test: https://prow.knative.dev/view/gcs/knative-prow/logs/ci-knative-sandbox-net-contour-continuous/1304066901449641984

```
    util.go:924: Error meeting response expectations: got unexpected status: 503, expected map[200:{}]
    util.go:924: HTTP/1.1 503 Service Unavailable
        Date: Thu, 10 Sep 2020 15:10:08 GMT
        Server: envoy
        Content-Length: 0
```

If I had to offer a guess this is because of our workaround for https://github.com/knative-sandbox/net-certmanager/issues/44

**Comment by tcnghia** [comment]
We could add a field `CanIgnoreProbe` (or similar) to allow relaxation of the probing contract. The default behavior for unspecified is backward compatible (required probe), and when it is set impls can choose to do what they want?

One thing I am not sure is whether that would have unintended consequence with composition.

**Comment by mattmoor** [comment]
The current elision of probes would have undesirable interactions with composition.  This workaround is to scope the elision to just http01 challenges by the Route controller until @ZhiminXiang can fix the issue.

**Comment by mattmoor** [comment]
I suspect that the latest failure is this as well, since it touches path (dispatch/path_and_percentage): https://prow.knative.dev/view/gcs/knative-prow/logs/ci-knative-sandbox-net-contour-continuous/1305470955987931136

**Comment by dprotaso** [comment]
Closing as test is stable
