### ISSUE TITLE
After using contour, how to observe whether knative enters serve mode?

### ISSUE THREAD

**Issue by Bryce-huang** [knative-extensions/net-contour#998]
After using contour, I saw that knative is always in proxy mode. Is this related to the implementation of net-contour?

Ref: https://knative.dev/docs/serving/architecture/#networking-layer-and-ingress

**Comment by dprotaso** [comment]
If you're looking at the internal resources (ServerlessService) and seeing Proxy/Serve mode then that's configuring whether the activator is in the path. This is unrelated to Contour.

Details are here:
https://knative.dev/docs/serving/load-balancing/
https://knative.dev/docs/serving/load-balancing/target-burst-capacity/

Going to close this out - feel free to re-open on the [knative/serving](https://github.com/knative/serving) repo  if you have further questions about the activator etc.
